finch_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finch/', views.finch_index, name='index'),
    path('finch/<int:finch_id>/', views.finch_detail, name='detail'),
    path('finch/create/', views.FinchCreate.as_view(), name='finch_create'),
    path('finch/<int:pk>/update/', views.FinchUpdate.as_view(), name='finch_update'),
    path('finch/<int:pk>/delete/', views.FinchDelete.as_view(), name='finch_delete'),
    path('finch/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('finch/<int:finch_id>/assoc_toy/<int:feature_id>/', views.assoc_feature, name='assoc_feature'),
    
    # Features
    path('features/', views.FeatureList.as_view(), name='feature_index'),
    path('features/<int:pk>/', views.FeatureDetail.as_view(), name='feature_detail'),
    path('features/create/', views.FeatureCreate.as_view(), name='feature_create'),
    path('features/<int:pk>/update/', views.FeatureUpdate.as_view(), name='feature_update'),
    path('features/<int:pk>/delete/', views.FeatureDelete.as_view(), name='feature_delete'),
    
    # Photo URL
    path('finch/<int:finch_id>/add_photo/', views.add_photo, name='add_photo'),
    ]

main_app/models.py
from django.db import models
from django.urls import reverse


MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

CHAR = (
    ('Feathers', 'Feathers'),
    ('High metabolism', 'High metabolism'),
    ('A four-chambered heart', 'A four-chambered heart'),
    ('A beak with no teeth', 'A beak with no teeth'),
    ('A lightweight but strong skeleton', 'A lightweight but strong skeleton'),
    ('Production of hard-shelled egg', 'Production of hard-shelled egg')
)

LEVEL = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5')
)

# Create your models here.
class Features(models.Model):
    characteristic = models.CharField(max_length=100, choices=CHAR)
    strength = models.CharField(max_length=1, choices=LEVEL, default='1')  

    def __str__(self):
        return f'{self.get_strength_display()} at Strength: {self.strength}'
    
    def get_absolute_url(self):
        return reverse('feature_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    habitat = models.CharField(max_length=100)
    nesting = models.CharField(max_length=100)
    behavior = models.CharField(max_length=100)
    conservation = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    strength = models.ManyToManyField(Features)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})
    
class Feeding(models.Model):
    date = models.DateField(max_length=100)
    meal = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'
    
    # change the default sort
    class Meta:
        ordering = ['-date']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for finch_id: {self.finch_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
import uuid
import boto3
from .models import Finch, Features, Photo
from .forms import FeedingForm
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import  ListView, DetailView

S3_BASE_URL = 'https://s3.us-west-1.amazonaws.com/'
BUCKET = 'finchcollector2023'

# Create your views here.
from django.http import HttpResponse

# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def finch_index(request):
  finches = Finch.objects.all()
  return render(request, 'finches/index.html', { 'finches': finches })

def finch_detail(request, finch_id):
   # cat_id is coming from the url definition
   # in urls.py
   # <int:cat_id>
   finch = Finch.objects.get(id=finch_id)
#  inserting Feeding Form into the detail function
   feeding_form = FeedingForm()
   feature_finch_does_not_have = Features.objects.exclude(id__in = finch.strength.all().values_list('id'))
  #  print(finch)
   return render(request, 'finches/detail.html', 
                 {'finch': finch, 'feeding_form':feeding_form,
                  'features': feature_finch_does_not_have})

def add_feeding(request, finch_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.finch_id = finch_id
    new_feeding.save()
  return redirect('detail', finch_id=finch_id)

def assoc_feature(request, finch_id, feature_id):
   Finch.objects.get(id=finch_id).strength.add(feature_id)
   return redirect('detail', finch_id=finch_id)

def add_photo(request, finch_id):
  # photo-file will be the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
      s3 = boto3.client('s3')
      # need a unique "key" for S3 / needs image file extension too
      key = 'finchcollector2023/' + uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      # just in case something goes wrong
      try:
          s3.upload_fileobj(photo_file, BUCKET, key)
          # build the full url string
          url = f"{S3_BASE_URL}{BUCKET}/{key}"
          # we can assign to finch_id or cat (if you have a finch object)
          #  the below finch_id = finch_id refers to the finch_id from Finch Model
          Photo.objects.create(url=url, finch_id=finch_id)
      except:
          print('An error occurred uploading file to S3')
  return redirect('detail', finch_id=finch_id)

class FinchCreate(CreateView):
   model = Finch
   fields = ['name', 'habitat', 'nesting', 'behavior', 'conservation', 'description']

   def __str__(self):
      return self.name
   
   def get_absolute_url(self):
      return reverse('detail', kwargs={'finch_id': self.id})
   
class FinchUpdate(UpdateView):
   model = Finch
   fields = ['habitat', 'behavior', 'nesting']

class FinchDelete(DeleteView):
   model = Finch
   success_url = '/finch/'

class FeatureList(ListView):
  model = Features

class FeatureDetail(DetailView):
  model = Features

class FeatureCreate(CreateView):
  model = Features
  fields = '__all__'

class FeatureUpdate(UpdateView):
  model = Features
  fields = ['strength', 'characteristic']

class FeatureDelete(DeleteView):
  model = Features
  success_url = '/features/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr />
<p>Hire the Finch Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;FinchCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'feature_create' %}">Add Feature</a></li>
          <li><a href="{% url 'feature_index' %}">View All Features</a></li>
          <li><a href="{% url 'index' %}">View All My finches</a></li>
          <li><a href="{% url 'finch_create' %}">Add Finch</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="card">
  <div>
    {% for photo in finch.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

    <!-- uploading photo into server -->
    <form action="{% url 'add_photo' finch.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
  </form>
  </div>
  <div class="card-content">
    <span class="card-title">{{ finch.name }}</span>
    <p>Habitat: {{ finch.habitat }}</p>
    <p>Nesting: {{ finch.nesting }}</p>
    <p>Behavior: {{ finch.behavior }}</p>
    <p>Description: {{ finch.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'finch_update' finch.id %}">Edit</a>
    <a href="{% url 'finch_delete' finch.id %}">Delete</a>
  </div>
</div>
</div>
<div class="col s6">
  <!-- new code below -->
  
  <form action="{% url 'add_feeding' finch.id %}" method="post">
    {% csrf_token %}
    {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding">
  </form>
  <!-- new code above -->
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Meal</th></tr>
    </thead>
    <tbody>
      {% for feeding in finch.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Available Features</h3>
    {% if features.count %}
      {% for feature in features.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
             <span style="color: teal">{{ feature.characteristic }}</span> at strength level {{ feature.strength }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_feature' finch.id feature.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{finch.name}} Already already include all Features</h5>
    {% endif %}

    <h3>{{ finch.name }}'s Features</h3>
    {% if finch.strength.count %}
      {% for feature in finch.strength.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ feature.characteristic }} at strength level of  <span style="color: teal">{{ feature.strength }}</span> 
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Feature :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %} {% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
<div class="card">
  <a href="{% url 'detail' finch.id %}">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
      <p>Habitat: {{ finch.habitat }}</p>
      <p>Nesting: {{ finch.nesting }}</p>
      <p>Behavior: {{ finch.behavior }}</p>
      <p>Convervation: {{ finch.conservation }}</p>
      <p>Description: {{ finch.description }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} 

{% block content %}

<h1>Welcome to Finch Collector</h1>

{% endblock %}

main_app/templates/main_app/features_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Feature</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.characteristic }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'feature_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/features_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Features Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ features.characteristic }}</span>
        <p>Strength: {{ features.strength }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'feature_update' features.id %}">Edit</a>
        <a href="{% url 'feature_delete' features.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/features_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.characteristic}}</span></h1>
  {% else %}
    <h1>Add Features</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

  
<script>
  const selectEl = document.getElementById('id_characteristic');
  const selectEl1 = document.getElementById('id_strength');
  M.FormSelect.init(selectEl);
  M.FormSelect.init(selectEl1);
</script>
{% endblock %}

main_app/templates/main_app/features_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Features List</h1>

{% for feature in features_list %}
  <a href="{% url 'feature_detail' feature.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ feature.characteristic }}</span>
            <p>Strength: {{ feature.strength }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}

  {% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
  <h1>Add Finch</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <br>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}